## Notación

::: {.columns}
::: {.column width="50%"}
- Punto: $\require{color} \textcolor{PineGreen}{d}_{\small \textrm{2D}} = \begin{pmatrix} \textcolor{Orange}{a} \\ \textcolor{RedViolet}{b} \end{pmatrix}$ 

- Vector: $\require{color} \textcolor{LimeGreen}{\boldsymbol{\vec{p}}}_\textcolor{PineGreen}{d} = \textcolor{Orange}{a} \boldsymbol{\vec{i}} + \textcolor{RedViolet}{b} \boldsymbol{\vec{j}}$

$$
\textcolor{LimeGreen}{\boldsymbol{\vec{p}}}_\textcolor{PineGreen}{d}
= \begin{bmatrix} \textcolor{Orange}{a} \\ \textcolor{RedViolet}{b} \end{bmatrix}
$$


::: {.callout-note appearance="simple" title=""}
Los vectores y matrices serán distinguidos en **negrita**
:::


:::
::: {.column width="50%"}


```{.tikz width="100%"}
%%| filename: vector-def

\begin{tikzpicture}
  \definecolor{Black}{RGB}{0,0,0}
  \definecolor{Blue}{RGB}{46, 49, 146}              % pigment: {0.2, 0.2, 0.6}
  \definecolor{ForestGreen}{RGB}{21, 155, 82}       % web: {0.13, 0.55, 0.13}
  \definecolor{Orange}{RGB}{244, 110, 43}           % web color: {1.0, 0.65, 0.0}
  \definecolor{Maroon}{rgb}{0.76, 0.13, 0.28}       % brightmaroon
  \definecolor{Gray}{RGB}{145, 143, 143}            % html/cssgray: {0.5, 0.5, 0.5}
  \definecolor{PineGreen}{RGB}{0, 139, 114}         % hex: rgb(0, 139, 114)
  \definecolor{LimeGreen}{RGB}{141, 199, 62}        % green-yellow: {0.68, 1.0, 0.18}
  \definecolor{RedViolet}{RGB}{161, 36, 107}

  \tikzstyle{rvec}=[->,thick,LimeGreen,line cap=round]

  \def\gridstartx{-0.45}
  \def\gridstarty{-1.55}
  \def\gridendx{4.85}
  \def\gridendy{3.75}

  \draw[step=1mm, black!5!white] (\gridstartx,\gridstarty) grid (\gridendx, \gridendy);
  \draw[step=5mm, black!10!white] (\gridstartx,\gridstarty) grid (\gridendx, \gridendy);
  \draw[step=1cm, black!15!white] (\gridstartx, \gridstarty) grid (\gridendx, \gridendy);

  \def\ul{1.2}
  \def\R{4.5}
  \def\ang{30}
  \coordinate (O) at (0.75,.5);
  \coordinate (R) at (\ang:\R);
  \coordinate (X) at ({\R*cos(\ang)},.5);
  \coordinate (Y) at (0.75,{\R*sin(\ang)});
  
  %\node[above right=-2] at (R') {$(x,y)$};

  \draw[color=Orange,dashed,thick] (X) -- (R);
  \draw[color=RedViolet,dashed,thick] (Y) -- (R);
  
  % Punto d
  \node[fill=PineGreen,circle,inner sep=0.9,label={[color=PineGreen,above right]$d$}] (R') at (R) {};
  % Vector
  \draw[rvec] (O) -- (R') node[midway,left=5,above right=0] {${\boldsymbol{p}}$};
  
  % Ejes
  \draw[-,dashed,color=black]
    ({1.1*\R*cos(\ang)},0.5) -- (O) -- (0.75,{1.25*\R*sin(\ang)});
  
  \draw[<->,very thick,black]
    ({\ul+0.75},.5) node[scale=1,left=2,below left=0] {$\boldsymbol{\vec{i}}$} -- (O) --
    (.75,{\ul+0.5}) node[scale=1,below=2,below left=0] {$\boldsymbol{\vec{j}}$};
  
  %\draw pic[->,thick,"$\theta$",draw=black,angle radius=26,angle eccentricity=1.3]
  %  {angle = X--O--R};
  \draw[thick,color=Orange] (X)++(0,0.1) --++ (0,-0.2) node[scale=0.9,below=-1] {$a$};
  \draw[thick,color=RedViolet] (Y)++(0.1,0) --++ (-0.2,0) node[scale=0.9,left] {$b$};
  
\end{tikzpicture}
```


:::
:::


## Notación

::: {.columns}
::: {.column width="50%"}
- Punto: $\require{color} \textcolor{PineGreen}{d}_{\small \textrm{2D}} = \begin{pmatrix} \textcolor{Orange}{a} \\ \textcolor{RedViolet}{b} \end{pmatrix} \;$ 

- Coordenadas del vector respecto del marco de referencia $\textcolor{Blue}{A}$:
$$\require{color} {}^{\textcolor{Blue}{A}}{\boldsymbol{\textcolor{LimeGreen}{p}}_\textcolor{PineGreen}{d}} = \textcolor{Orange}{a} \textcolor{Blue}{\boldsymbol{\vec{i}}} + \textcolor{RedViolet}{b} \textcolor{Blue}{\boldsymbol{\vec{j}}}$$

:::
::: {.column width="50%"}


```{.tikz width="100%"}
%%| filename: vector-def2

\begin{tikzpicture}
  \definecolor{Black}{RGB}{0,0,0}
  \definecolor{Blue}{RGB}{46, 49, 146}              % pigment: {0.2, 0.2, 0.6}
  \definecolor{ForestGreen}{RGB}{21, 155, 82}       % web: {0.13, 0.55, 0.13}
  \definecolor{Orange}{RGB}{244, 110, 43}           % web color: {1.0, 0.65, 0.0}
  \definecolor{Maroon}{rgb}{0.76, 0.13, 0.28}       % brightmaroon
  \definecolor{Gray}{RGB}{145, 143, 143}            % html/cssgray: {0.5, 0.5, 0.5}
  \definecolor{PineGreen}{RGB}{0, 139, 114}         % hex: rgb(0, 139, 114)
  \definecolor{LimeGreen}{RGB}{141, 199, 62}        % green-yellow: {0.68, 1.0, 0.18}
  \definecolor{RedViolet}{RGB}{161, 36, 107}

  \tikzstyle{rvec}=[->,thick,LimeGreen,line cap=round]

  \def\gridstartx{-0.45}
  \def\gridstarty{-1.55}
  \def\gridendx{4.85}
  \def\gridendy{3.75}

  \draw[step=1mm, black!5!white] (\gridstartx,\gridstarty) grid (\gridendx, \gridendy);
  \draw[step=5mm, black!10!white] (\gridstartx,\gridstarty) grid (\gridendx, \gridendy);
  \draw[step=1cm, black!15!white] (\gridstartx, \gridstarty) grid (\gridendx, \gridendy);

  \def\ul{1.2}
  \def\R{4.5}
  \def\ang{30}
  \coordinate (O) at (0.75,.5);
  \coordinate (R) at (\ang:\R);
  \coordinate (X) at ({\R*cos(\ang)},.5);
  \coordinate (Y) at (0.75,{\R*sin(\ang)});
  
  %\node[above right=-2] at (R') {$(x,y)$};

  \draw[color=Orange,dashed,thick] (X) -- (R);
  \draw[color=RedViolet,dashed,thick] (Y) -- (R);
  
  % Punto d
  \node[fill=PineGreen,circle,inner sep=0.9,label={[color=PineGreen,above right]$d$}] (R') at (R) {};
  % Vector
  \draw[rvec] (O) -- (R') node[midway,left=5,above right=0] {${\boldsymbol{p}}$};
  
  % Ejes
  \draw[<->,very thick,color=Blue]
    ({1.2*\R*cos(\ang)},0.5) node[below left] {\footnotesize $\textcolor{Blue}{\boldsymbol{\vec{i}}}$}
    -- (O) node[below left] {$\textcolor{Blue}{\{ \boldsymbol{A} \}}$}
    -- (0.75,{1.3*\R*sin(\ang)}) node[above] {\footnotesize $\textcolor{Blue}{\boldsymbol{\vec{j}}}$};
    
  
  % \draw[<->,very thick,black]
  %   ({\ul+0.75},.5) node[scale=1,left=2,below left=0] {$\boldsymbol{\vec{i}}$} -- (O) --
  %   (.75,{\ul+0.5}) node[scale=1,below=2,below left=0] {$\boldsymbol{\vec{j}}$};
  
  %\draw pic[->,thick,"$\theta$",draw=black,angle radius=26,angle eccentricity=1.3]
  %  {angle = X--O--R};
  \draw[thick,color=Orange] (X)++(0,0.1) --++ (0,-0.2) node[scale=0.9,below=-1] {$a$};
  \draw[thick,color=RedViolet] (Y)++(0.1,0) --++ (-0.2,0) node[scale=0.9,left] {$b$};
  
\end{tikzpicture}
```


:::
:::


## Notación {.smaller}

::: {.columns}
::: {.column width="50%"}

- Un vector tiene una representación por cada marco de referencia
- Todas "*apuntan*" al mismo punto $\textcolor{PineGreen}{d}$:

$$\require{color} {}^{\textcolor{Blue}{A}}{\boldsymbol{\textcolor{LimeGreen}{p}}} \equiv \require{color} {}^{\textcolor{Orange}{B}}{\boldsymbol{\textcolor{LimeGreen}{p}}} \equiv \require{color} {}^{\textcolor{Gray}{C}}{\boldsymbol{\textcolor{LimeGreen}{p}}} \equiv \require{color} {}^{\textcolor{Maroon}{D}}{\boldsymbol{\textcolor{LimeGreen}{p}}}$$

- Las componentes pueden ser distintas

$$
{\small
\textcolor{Blue}{\sideset{^{A}}{}{\begin{bmatrix}
    \textcolor{black}{2.1} \\
    \textcolor{black}{1.0}
\end{bmatrix}}} \equiv
\textcolor{Orange}{\sideset{^{B}}{}{\begin{bmatrix}
    \textcolor{black}{-1.7} \\
    \textcolor{black}{0.6}
\end{bmatrix}}} \equiv
\textcolor{Gray}{\sideset{^{C}}{}{\begin{bmatrix}
    \textcolor{black}{1.5} \\
    \textcolor{black}{0.6}
\end{bmatrix}}} \equiv
\textcolor{Maroon}{\sideset{^{D}}{}{\begin{bmatrix}
    \textcolor{black}{-1.5} \\
    \textcolor{black}{1.0}
\end{bmatrix}}}
}
$$


:::
::: {.column width="50%"}


```{.tikz width="100%"}
%%| filename: vector-ref-frame

\begin{tikzpicture}
  \definecolor{Black}{RGB}{0,0,0}
  \definecolor{Blue}{RGB}{46, 49, 146}              % pigment: {0.2, 0.2, 0.6}
  \definecolor{ForestGreen}{RGB}{21, 155, 82}       % web: {0.13, 0.55, 0.13}
  \definecolor{Orange}{RGB}{244, 110, 43}           % web color: {1.0, 0.65, 0.0}
  \definecolor{Maroon}{rgb}{0.76, 0.13, 0.28}       % brightmaroon
  \definecolor{Gray}{RGB}{145, 143, 143}            % html/cssgray: {0.5, 0.5, 0.5}
  \definecolor{PineGreen}{RGB}{0, 139, 114}         % hex: rgb(0, 139, 114)
  \definecolor{LimeGreen}{RGB}{141, 199, 62}        % green-yellow: {0.68, 1.0, 0.18}

  %\colorlet{xcol}{blue!70!black}
  % \colorlet{xcol'}{xcol!50!red!80!black}
  % \colorlet{veccol}{green!45!black}
  % \tikzstyle{vector}=[->,thick,veccol,line cap=round]
  \tikzstyle{rvec}=[->,thick,LimeGreen,line cap=round]

  %\small
  \def\L{0.8}
  \def\R{2.3}
  \def\ang{26}
  \def\thet{-52}
  \coordinate (O) at (0,0);
  \coordinate (O1) at (3.8,0.4);
  \coordinate (O2) at (1.5,2.5);
  \coordinate (O3) at (2.2,-0.8);
  \coordinate (R) at (\ang:\R);

  \def\gridstartx{-0.45}
  \def\gridstarty{-1.55}
  \def\gridendx{4.85}
  \def\gridendy{3.75}
  
  %\draw[step=1mm, line width=0.1mm, black!5!white] (\gridstartx,\gridstarty) grid (\gridendx, \gridendy);
  %\draw[step=5mm, line width=0.2mm, black!10!white] (\gridstartx,\gridstarty) grid (\gridendx, \gridendy);
  %\draw[step=1cm, line width=0.3mm, black!15!white] (\gridstartx, \gridstarty) grid (\gridendx, \gridendy);
  \draw[step=1mm, black!5!white] (\gridstartx,\gridstarty) grid (\gridendx, \gridendy);
  \draw[step=5mm, black!10!white] (\gridstartx,\gridstarty) grid (\gridendx, \gridendy);
  \draw[step=1cm, black!15!white] (\gridstartx, \gridstarty) grid (\gridendx, \gridendy);

  % Punto d
  \node[fill=PineGreen,circle,inner sep=0.9,label={[color=PineGreen,anchor=south west]$d$}] (R') at (R) {};
  
  % O
  \draw[rvec] (O) -- (R') node[midway,above] {\footnotesize ${}^{\textcolor{Blue}{\boldsymbol{A}}}{\boldsymbol{p}}$};
  \draw[<->,thick,color=Blue] (\L,0) node[below] {\scriptsize $\boldsymbol{\vec{i}}$} --
                   (O) node[below left=-3] {\footnotesize $\boldsymbol{A}$} --
                   (0,\L) node[left=-1] {\scriptsize $\boldsymbol{\vec{j}}$};
  
  % O1
  \begin{scope}[shift={(O1)}]
    \draw[rvec] (0,0) -- (R') node[midway,above] {\footnotesize ${}^{\textcolor{Orange}{\boldsymbol{B}}}{\boldsymbol{p}}$};
    \draw[<->,thick,color=Orange] (\L,0) node[below=-2] {\scriptsize $\boldsymbol{\vec{i}}$} --
                     (0,0) node[below left=-2] {\footnotesize $\boldsymbol{B}$} --
                     (0,\L) node[left=-2] {\scriptsize $\boldsymbol{\vec{j}}$};
  \end{scope}
  
  % O2
  \begin{scope}[shift={(O2)}]
    \draw[rvec] (0,0) -- (R') node[midway,right] {\footnotesize ${}^{\textcolor{Gray}{\boldsymbol{C}}}{\boldsymbol{p}}$};
    \draw[<->,thick,color=Gray] (\L,0) node[above] {\scriptsize $\boldsymbol{\vec{j}}$} --
                     (0,0) node[above left=-4] {\footnotesize $\boldsymbol{C}$} --
                     (0,-\L) node[left] {\scriptsize $\boldsymbol{\vec{i}}$};
  \end{scope}
  
  % O3
  \begin{scope}[shift={(O3)}]
    \draw[rvec] (0,0) -- (R') node[midway,left] {\footnotesize ${}^{\textcolor{Maroon}{\boldsymbol{D}}}{\boldsymbol{p}}$};
    \draw[<->,thick,color=Maroon] (\thet:\L) node[below left=-2] {\scriptsize $\boldsymbol{\vec{i}}$} --
                     (0,0) node[left=-2] {\footnotesize $\boldsymbol{D}$} --
                     (\thet+90:\L) node[above=-2] {\scriptsize $\boldsymbol{\vec{j}}$};
  \end{scope}
  
\end{tikzpicture}
```


:::
:::




## Transformaciones lineales

Para un vector $\boldsymbol{p} \in \mathbb{R}^{n}$, son funciones de la forma:

$$
f(\boldsymbol{p}) = \boldsymbol{T} ~\boldsymbol{p}
$$

donde $\boldsymbol{T}$ es una matrix de $n \times n$

<br>

> [*Propiedad*]{.underline}: Se pueden encadenar como producto de matrices
$$f_3(f_2(f_1(\boldsymbol{p}))) = \boldsymbol{T}_3 \left( \boldsymbol{T}_2  \left( \boldsymbol{T}_1 ~\boldsymbol{p} \right) \right) = \boldsymbol{T}_3 ~\boldsymbol{T}_2 ~\boldsymbol{T}_1  ~\boldsymbol{p}$$

## Transformaciones lineales

Ejemplo para 2 dimensiones ($n = 2$):

$$ \boldsymbol{T} = \begin{bmatrix} \textcolor{red}{a} & \textcolor{lime}{b} \\ \textcolor{blue}{c} & \textcolor{magenta}{d} \end{bmatrix} $$

entonces, dado $\boldsymbol{p} =  \begin{bmatrix} x_1 & y_1  \end{bmatrix}^\top$

$$
f(\boldsymbol{p}) = \boldsymbol{T} ~\boldsymbol{p} =
\begin{bmatrix} \textcolor{red}{a} & \textcolor{lime}{b} \\ \textcolor{blue}{c} & \textcolor{magenta}{d} \end{bmatrix}
\begin{bmatrix} x_1 \\ y_1 \end{bmatrix} =
\begin{bmatrix} \textcolor{red}{a} ~x_1 + \textcolor{lime}{b} ~y_1 \\ \textcolor{blue}{c} ~x_1 + \textcolor{magenta}{d} ~y_1 \end{bmatrix} =
\begin{bmatrix} x_2 \\ y_2 \end{bmatrix}
$$
