# Clases

::: {.callout-note}
El siguiente cronograma puede sufrir modificaciones o ser actualizado con el correr del cursado
:::

| Semana | Fecha | Tema | [Slides]{title="Slides"} | [Notas]{title="Notas"} | [T.]{title="Teórico"} | [Lab.]{title="Laboratorio"} | [T.R.]{title="Taller de resolución"} |
|:------:|--------|--------|:------:|:------:|:------:|:------:|:------:|
|1  | 17/03 | Introducción a la Robótica. Organización de la materia. Herramientas de trabajo. | [🖥️](/clases/01/slides.qmd "Slides"){aria-label="Clase 1 slides"} | [📝](/clases/01/notas.qmd "Notas"){aria-label="Clase 1 notas"} | |
|2  | 24/03 | **Feriado 24 de Marzo - Día nacional de la memoria por la verdad y la justicia** | |
|3  | 31/03 | ROS2: Definición y propósito. Conceptos básicos (nodos, *topics*, mensajes, contexto). Instalación y ejemplos básicos. | [🖥️](/clases/02/slides.qmd "Slides"){aria-label="Clase 2 slides"} | [📝](/clases/02/notas.qmd "Notas"){aria-label="Clase 2 notas"} | | [🧪](/clases/02/lab.html "Lab"){aria-label="Clase 2 lab"} | |
|4  | 07/04 | ROS2: Componentes adicionales (parámetros, servicios, acciones). Ejercicios de aplicación. | [🖥️](/clases/03/slides.qmd "Slides"){aria-label="Clase 3 slides"} | [📝](/clases/03/notas.qmd "Notas"){aria-label="Clase 3 notas"} | | [🧪](/clases/03/lab.html "Lab"){aria-label="Clase 3 lab"} | |
|5  | 14/04 | ROS2 _R.E.P._'s. Entorno y *workspace*. Paquetes y librería `rclpy`: programación de nodos. Callbacks. Compilación y ejecución. | [🖥️](/clases/04/slides.qmd "Slides"){aria-label="Clase 4 slides"} | [📝](/clases/04/notas.qmd "Notas"){aria-label="Clase 4 notas"} | | [🧪](/clases/04/lab.html "Lab"){aria-label="Clase 4 lab"} | |
|6  | 21/04 | Programación Orientada a Objetos en ROS2. Ejemplos de aplicación: Nodos y parámetros. *Logging*. | [🖥️](/clases/05/slides.qmd "Slides"){aria-label="Clase 5 slides"} | [📝](/clases/05/notas.qmd "Notas"){aria-label="Clase 5 notas"} | | [🧪](/clases/05/lab.html "Lab"){aria-label="Clase 5 lab"} | |
|7  | 28/04 | Sistema `roslaunch`, aplicación en proyectos de ROS2. Argumentos. Práctica integradora *unidad 1*.  | [🖥️](/clases/06/slides.qmd "Slides"){aria-label="Clase 6 slides"} | [📝](/clases/06/notas.qmd "Notas"){aria-label="Clase 6 notas"} | | [🧪](/clases/06/lab.html "Lab"){aria-label="Clase 6 lab"} | |
|8  | 05/05 | Traslación y rotación 2D. Pose y orientación 3D en ROS. Librería `tf2` y publicación de transformaciones. | [🖥️](/clases/07/slides.qmd "Slides"){aria-label="Clase 7 slides"} | [📝](/clases/07/notas.qmd "Notas"){aria-label="Clase 7 notas"} | | [🧪](/clases/07/lab.html "Lab"){aria-label="Clase 7 lab"} | |
|9  | 12/05 | _U.R.D.F._: Representación de geometría de un robot. Uso de _XACRO_, `robot_state_publisher` y `tf2`. | [🖥️](/clases/08/slides.qmd "Slides"){aria-label="Clase 8 slides"} | [📝](/clases/08/notas.qmd "Notas"){aria-label="Clase 8 notas"} | | | [🛠️](/clases/08/tres.html "Taller de resolución"){aria-label="Clase 8 Taller de resolución"}
|10 | 19/05 | *Gazebo*: Entorno de simulación. Paquete `ros2_control` y `gz_ros2_contol`. *Hardware interface* y controladores. | [🖥️](/clases/09/slides.qmd "Slides"){aria-label="Clase 9 slides"} | [📝](/clases/09/notas.qmd "Notas"){aria-label="Clase 9 notas"} | | | [🛠️](/clases/09/tres.html "Taller de resolución"){aria-label="Clase 9 Taller de resolución"}
|11 | 26/05 | Cinemática y locomoción: modelo cinemático de un robot diferencial. Cinemática inversa y directa. | |
|12 | 02/06 | Odometría: Cálculo de posición en base al modelo cinemático directo. | |
|13 | 09/06 | Percepción: sensores. Clasificación y caracterización. Tipos y ejemplos según variable a medir. | |
|14 | 16/06 | Simulación de sensores en Gazebo | |
|15 | 23/06 | Presentación entregable 1 | |

: {.striped .hover tbl-colwidths="[8, 8, 60, 8, 8, 8]"}
