project:
  type: website
  output-dir: ../public
  preview:
    port: 4200
    browser: false

lang: es

website:
  title: "Robótica 2026"
  sidebar:
    # logo: https://sinc.unl.edu.ar/wp-content/themes/sinci/img/sinc-logo.png
    logo-alt: "sinc(i) - UNL - CONICET"
    search: false
    alignment: center
    border: true
    header: |
      <h2> [Universidad Nacional del Litoral](https://www.unl.edu.ar/) (UNL) <br> </h2>
      <h3> [Facultad de Ingeniería y Ciencias Hídricas](https://www.fich.unl.edu.ar/) (FICH) </h3> <br> \
      **Tecnicatura Universitaria en Automatización y Robótica (TUAR)** <br> \
      ![](https://sinc.unl.edu.ar/wp-content/themes/sinci/img/sinc-logo.png)

  bread-crumbs: true

format:
  html:
    page-layout: full
    theme: litera
    css: sh-highlight.css
